### من الخوارزميات المعروفة والمستخدمة في التعلم الالي والتعلم العميق

### تقوم الخوارزمية بالتدريب عن طريق ضبط الاوزان في العفد وتمريرها الى الطبقات الاخرى للتدريب واخراج التائج

In [1]:
from sklearn.neural_network import MLPClassifier

In [2]:
import numpy as np

In [9]:
xs = np.array( [
    0,0,
    0,1,
    1,0,
    1,1
]).reshape(4,2)
xs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [8]:
ys = np.array([0,1,1,0]).reshape(4,)
ys

array([0, 1, 1, 0])

In [23]:
model = MLPClassifier( max_iter=10000  ,  hidden_layer_sizes=(8,2))

In [24]:
model.fit(xs,ys)

MLPClassifier(hidden_layer_sizes=(8, 2), max_iter=10000)

In [25]:
model.score(xs,ys)

0.75

In [26]:
model.predict(xs)

array([0, 1, 1, 1])